version: "3"

services:
  app:
    image: mcr.microsoft.com/devcontainers/java:1-11-bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:azurite

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: unless-stopped